### ISSUE TITLE
Server Error

### ISSUE THREAD

**Issue by azizimo** [stackkit/laravel-google-cloud-scheduler#19]
Thank you for creating this package, we are using it, 

I have two question. 
1) We have many jobs that run through the schedule:run. we are getting 
500 Server Error, 
The server encountered an error and could not complete your request, Please try again in 30 seconds. 
Any fix please? 
2) Any way to run multiple queue worker to speed up the processing of the queue? Or you just add multiple command to run queue:work for the same queue? 

Something like this. 
`$schedule->command('queue:work --queue=email-notifications,daily-csv-export,default --timeout=3600 --tries=3')
            ->everyMinute()
            ->withoutOverlapping()
            ->runInBackground();

$schedule->command('queue:work --queue=email-notifications,daily-csv-export,default --timeout=3600 --tries=3')
            ->everyMinute()
            ->withoutOverlapping()
            ->runInBackground();

$schedule->command('queue:work --queue=email-notifications,daily-csv-export,default --timeout=3600 --tries=3')
            ->everyMinute()
            ->withoutOverlapping()
            ->runInBackground();
`
Thank you

**Comment by marickvantuil** [comment]
> We have many jobs that run through the schedule:run. we are getting
500 Server Error,
The server encountered an error and could not complete your request, Please try again in 30 seconds.
Any fix please?

This is using App Engine, I think? There is some kind of exception happening while processing the job. Do you have detailed logs (e.g. a laravel.log, or a Sentry/Bugsnag/whatever other error tracker)?

> Any way to run multiple queue worker to speed up the processing of the queue? Or you just add multiple command to run queue:work for the same queue?

Personally, I wouldn't run the Laravel queue using a cronjob/scheduler. I actually have a dedicated package that uses Cloud Tasks as a Laravel queue driver. The added benefit of Cloud Tasks is that you can configure how many tasks are dispatched to your application:

<img width="557" alt="Screenshot 2022-09-30 at 16 44 54" src="https://user-images.githubusercontent.com/647007/193295790-11670a7e-0348-4207-a2e5-18274a36bdc0.png">

Otherwise, I think your approach is fine too, it seems like it could work:

<img width="682" alt="Screenshot 2022-09-30 at 16 48 17" src="https://user-images.githubusercontent.com/647007/193296441-847fb1a3-d2d5-48ee-a11a-a4d104fc7782.png">

But a big note here, I have never tested this package to run `queue:work` so results may vary ;-)

**Comment by azizimo** [comment]
Thank you @marickvantuil here is the log errors from google cloud logger 

- When the jobs run or  when we run a custom command manually through the link stuck on this one any ideas that can help thank you?

This request caused a new process to be started for your application, and thus caused your application code to be loaded for the first time. This request may thus take longer and use more CPU than a typical request for your application.

Process terminated because the request deadline was exceeded. Please ensure that your HTTP server is listening for requests on 0.0.0.0 and on the port defined by the PORT environment variable. (Error code 123)

Thank you for the advice we will try to shift to google cloud task because we have lot of queue and we need better solution. 

I have closed the issue thank you

**Comment by azizimo** [comment]
@marickvantuil can you please share the package that you are using to run queue thank you 🙏

**Comment by marickvantuil** [comment]
> When the jobs run or when we run a custom command manually through the link stuck on this one any ideas that can help thank you?

Sorry, what do you mean?

> This request caused a new process to be started for your application, and thus caused your application code to be loaded for the first time

This makes sense as the `runInBackground` part starts a new process. It will keep running forever. Maybe try this option?

<img width="695" alt="Screenshot 2022-10-04 at 18 40 44" src="https://user-images.githubusercontent.com/647007/193877611-7717d8af-3555-4435-a8fe-8a1c25a02606.png">

**Comment by azizimo** [comment]
Thank you I will try this options. We get this error when we run command via postman manually
