### ISSUE TITLE
The given OpenID token is not valid

### ISSUE THREAD

**Issue by VoordeMensen** [stackkit/laravel-google-cloud-scheduler#5]
I'm receiving the error `The given OpenID token is not valid` - I've added a service account and granted that service account `Cloud Scheduler` Admin rights. What am I missing?

**Comment by marickvantuil** [comment]
Hey, I tested this and actually got the same error and have  sneaking suspicion we might be running into the same issue.

Can you please go to Google Cloud Scheduler, find the scheduled job, edit the scheduled job and click on _SHOW MORE_. There make sure the **audience** field contains the value set in `STACKKIT_CLOUD_SCHEDULER_APP_URL` (this is what we check that should match)

**Comment by VoordeMensen** [comment]
Ahh yes that works! Thanks Marick! 💃 

Raises another issue though: my command of very obvious choice is `php artisan schedule:run` but that throws an `undefined offset` error in TaskHandler.php after the first iteration of `$this->schedule->events`:

```
return substr($parts[1], 2, strlen($parts[1]));
```

So I might not totally understand the concept: doesn't the scheduler just simply run an artisan command? Why would it loop over all scheduled events? 

Best, V

**Comment by marickvantuil** [comment]
> So I might not totally understand the concept: doesn't the scheduler just simply run an artisan command? Why would it loop over all scheduled events?

Understandable! The idea I had with the package was that it could do the same as Laravel's `schedule:run` but without having to run it every minute. It allows you to schedule something every hour while still supporting before/after callbacks, withoutOverlapping, skip, etc, eg the features that `schedule:run` offers. The reason it loops through all events is so it can find these configurations that are in the console kernel. 

Since building it I have started to wonder if it's not just easier to do what you've done and simply add `schedule:run` to run every minute. One thing I can think of is that `schedule:run` starts a separate processes for each command and I'm not entirely sure how GCR handles that. (It might just be fine)

> but that throws an undefined offset error

Hm from some quick testing I cannot reproduce this. Do you have a small example/steps I can follow to reproduce it?

Apologies if there are more things not working as intended. I had planned to use this for a client but some things got delayed so I haven't used it myself yet with a more 'realistic' project/setting.

**Comment by VoordeMensen** [comment]
Some context: I have a console kernel with several closures like this: 

```
    /**
     * Define the application's command schedule.
     *
     * @param  \Illuminate\Console\Scheduling\Schedule  $schedule
     * @return void
     */
    protected function schedule(Schedule $schedule)
    {
      $schedule->call(function() {
        doStuff();
       })->everyMinute();

      $schedule->call(function() {
        doMoreStuff();
       })->everyFiveMinutes();
    }
```

I've configured Cloud Scheduler like this: 

![image](https://user-images.githubusercontent.com/35703448/103168925-b579ed80-4837-11eb-89d7-0ee890d97c2f.png)

It raises this error:

```
Dec 27 11:32:00 localhost php: [2020-12-27 11:32:00] production.ERROR: Undefined offset: 1 {"exception":"[object] (ErrorException(code: 0): Undefined offset: 1 at /workspace/vendor/stackkit/laravel-google-cloud-scheduler/src/TaskHandler.php:113)
Dec 27 11:32:00 localhost php: #0 /workspace/vendor/stackkit/laravel-google-cloud-scheduler/src/TaskHandler.php(113): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError(8, 'Undefined offse...', '/workspace/vend...', 113, Array)
```

Maybe it's because my ``$event->command`` is empty?

I think I'll just run ``schedule:run`` to see how GCE picks it up.

**Comment by marickvantuil** [comment]
Thanks, I have pushed a new version with a fix for this. Can you try it out and report if it has solved the issue?

**Comment by VoordeMensen** [comment]
Yes now it works! Great, thanks!
